### ISSUE TITLE
Space key?

### ISSUE THREAD

**Issue by horacehylee** [golang-design/hotkey#13]
Thanks for the library, it works like a charm.

Just wanted to ask why `Space` key is not available with this package?

I could make a PR to add the space key here if wanted

**Comment by changkun** [comment]
Hi, I don't remember why space key was not there. Probably forgotten. I think adding a space key would be helpful. Hence PR welcome, make sure that the PR is sent for all platforms instead of a specific one.

Note that for any keys that are not there can always use the raw keycode and be converted to `hotkey.Key`. Similar to what was discussed here https://github.com/golang-design/hotkey/issues/2#issuecomment-877767223
